#!/usr/bin/env sh
rlwrap ocaml ../../shared/environment.cmo ../../shared/utils.cmo ../../shared/syntax/absyn.cmo ../../shared/syntax/parser.cmo ../../shared/syntax/lexer.cmo instructions.cmo compiler.cmo codegen.cmo slothc.cmo 
